<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <link rel="stylesheet" href="styles.css">
  <title>BANK WITH EASE!</title>
</head>

<body background="black">
  <nav class="navbar navbar-expand-lg navbar-dark  border border-white" style="background-color: #0A1931;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><em>SPARKS BANK</em></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="HOME_PAGE.php">Home</a>
          <a class="nav-link" href="transfermoney.php">Transfer money</a>
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
        </div>
      </div>
    </div>
  </nav>
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel" style="height: 10%;">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://images.pexels.com/photos/1422408/pexels-photo-1422408.jpeg?cs=srgb&dl=pexels-croberin-photography-1422408.jpg&fm=jpg" width="100" height="650" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://c0.wallpaperflare.com/preview/227/603/787/arrow-bank-banking-bar.jpg" width="100" height="650" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://image.freepik.com/free-vector/digital-credit-card-payment-background-fast-technology-style_1017-30674.jpg" width="100" height="650" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade"  data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade"  data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative tm" style="background-color: #DDDDDD;">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">BANKING</strong>
          <h3 class="mb-0">TRANSFER MONEY</h3>
          <p class="card-text mb-auto">Tranfer now within Seconds</p>
          <a href="transfermoney.php" class="stretched-link">CLICK HERE</a>
        </div>
        <div class="col-auto d-none d-lg-block">
         <img class="bd-placeholder-img" width="350" height="250" src="https://mms.businesswire.com/media/20180201005671/en/638366/5/BiP_money_transfer.jpg" alt="">
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative cust" style="background-color: #DDDDDD;">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">CUSTOMERS</strong>
          <h3 class="mb-0">CUSTOMER DATABASE</h3>
          <p class="mb-auto">View all the customer related information </p>
          <a href="#" class="stretched-link">CLICK HERE</a>
        </div>
        <div class="col-auto d-none d-lg-block">
         <img class="bd-placeholder-img" width="350" height="250" src="https://planful.com/wp-content/uploads/customers.jpg" alt="">

        </div>
      </div>
    </div>
  </div>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">Made By
    <a href="https://mdbootstrap.com/"> Pranit Mittal</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->


  </body>

</html>